<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504013046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE virtual_tour (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE virtual_tour_artwork (virtual_tour_id INT NOT NULL, artwork_id INT NOT NULL, PRIMARY KEY (virtual_tour_id, artwork_id))');
        $this->addSql('CREATE INDEX IDX_4FF3C62A239A5E8C ON virtual_tour_artwork (virtual_tour_id)');
        $this->addSql('CREATE INDEX IDX_4FF3C62ADB8FFA4 ON virtual_tour_artwork (artwork_id)');
        $this->addSql('ALTER TABLE virtual_tour_artwork ADD CONSTRAINT FK_4FF3C62A239A5E8C FOREIGN KEY (virtual_tour_id) REFERENCES virtual_tour (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE virtual_tour_artwork ADD CONSTRAINT FK_4FF3C62ADB8FFA4 FOREIGN KEY (artwork_id) REFERENCES artwork (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE virtual_tour_artwork DROP CONSTRAINT FK_4FF3C62A239A5E8C');
        $this->addSql('ALTER TABLE virtual_tour_artwork DROP CONSTRAINT FK_4FF3C62ADB8FFA4');
        $this->addSql('DROP TABLE virtual_tour');
        $this->addSql('DROP TABLE virtual_tour_artwork');
    }
}
